title: MoonLite
description: Hosted updates for MoonLite, a Vintage Story Mod Launcher
github_username: phahx
theme_accent: "#F47B49"
latest_download_link: "https://github.com/phahx/moonlite/releases/latest"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
