title: MoonLite
description: Hosted updates for MoonLite, a Vintage Story Mod Launcher
github_username: phahx
theme_accent: "#F47B49"
url: https://phahx.github.io
baseurl: /moonlite
future: true
timezone: America/New_York
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
